version: 2

sources:
  # --- PREMIER DATASET : raw_database ---
  - name: donnees_brutes
    database: les-fourcasters
    schema: raw_database
    tables:
      - name: open_meteo_archive
        description : "Données open meteo complétées automatiquement"

      - name: open_meteo_20000101_to_20260731
        description : "Historique des données open meteo de 2000 à 2026 fait par mes collègues"
        columns:
          - name: row_hash
            tests:
              - not_null
              - unique

      - name: raw_daily_weather
        description: "Données météo incrémentales quotidiennes"
        columns:
          - name: row_hash
            description: "Clé unique générée par hachage de la ville et de la date"
            tests:
              - not_null
              - unique
      
      - name: odisse_canicule_nb_jours_departement
        description: "Le nombre de jours de canicules annuels, selon la définition du système d'alerte canicule et santé, est calculé à partir des données de températures minimales et maximales fournies par Météo-France pour une station de référence par département."

      - name: odisse_canicule_population_concerne_departement
        description: "Taille de la population exposée à au moins un jour de canicule dans l'année, selon la définition du système d'alerte canicule et santé, calculé à partir des données de températures minimales et maximales fournies par Météo-France pour une station de référence par département."

      - name: odisse_canicule_deces_attribuable_departement
        description: "Nombre et fraction de décès toutes causes attribuables à la chaleur chaque année (tous âges et 75 ans et plus), pendant la période de surveillance (1er Juin - 15 Septembre) et pendant les canicules."
      
      - name: odisse_canicule_severite_departement
        description: "Sévérité annuelle des canicules pour chaque année et département. La sévérité est définie, à l'échelle départementale, comme la somme des écarts des températures minimale et maximale observées aux seuils d'alerte associés, pendant les jours de canicule."

  # --- DEUXIÈME DATASET : imports_csv ---
  - name: referentiels
    database: les-fourcasters
    schema: imports_csv
    tables:
      - name: departements_latitude_longitude
        description: "Référentiel des communes avec coordonnées et régions"