name: Run ELT Pipeline

on:
  schedule:
    - cron: '21 2 * * *' 
  workflow_dispatch:      

jobs:
  run-elt:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: ☁️ Authentification GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.CLAWYUNKAI_GCP_SA_KEY }}'

      - name: ⚡ Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: 📦 Installation des dépendances
        working-directory: ./clawyunkai
        run: uv sync

      - name: 🚀 1. Ingestion Python (API -> BigQuery)
        working-directory: ./clawyunkai
        run: uv run python load_openmeteo_api.py

      - name: 🛠️ 2. Transformation dbt (Staging + Marts)
        working-directory: ./clawyunkai/wild_data_hub
        run: uv run dbt run --profiles-dir .